# Generated by Django 2.2.14 on 2020-09-23 16:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_checkout_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
