# Generated by Django 2.2.14 on 2020-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_checkout_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Recieved', 'Recieved'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped'), ('Packaging', 'Packaging'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
