# Generated by Django 2.2.14 on 2020-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('computers', 'Computers')], max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('camera_and_photo', 'Camera & Photo'), ('laptops', 'Laptops'), ('wireless', 'wireless')], max_length=2000, null=True),
        ),
    ]
